version: '1'
services:
  mysql-db:
    container_name: streamx-mysql-docker
    image: streamx/mysql:${v_num}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      TZ: Asia/Shanghai     # 指定时区
    stdin_open: true
    tty: true

  stream:
    container_name: stream-service-docker
    image: streamx/streamx-console-service:${v_num}
    volumes:
      - conf:/opt/streamx/conf
    ports:
      - "10000:10000"
    environment:
      TZ: Asia/Shanghai     # 指定时区
    stdin_open: true
    tty: true
    depends_on:
      - "mysql-db"

volumes:
  conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/work/streamx/docker/workspace

